#!/bin/bash
# Dokploy Auto-Deploy Script for SiteSpark
# Deploy user websites automatically to Dokploy

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
DOKPLOY_HOST="${DOKPLOY_HOST:-localhost}"
DOKPLOY_PORT="${DOKPLOY_PORT:-3000}"
DOKPLOY_API="http://${DOKPLOY_HOST}:${DOKPLOY_PORT}/api"
PROJECT_NAME="${PROJECT_NAME:-sitespark}"
WEBSITES_DIR="${WEBSITES_DIR:-./websites}"

# Logging functions
log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Check dependencies
check_dependencies() {
    log_info "Checking dependencies..."
    
    command -v curl >/dev/null 2>&1 || { log_error "curl is required but not installed."; exit 1; }
    command -v docker >/dev/null 2>&1 || { log_error "docker is required but not installed."; exit 1; }
    
    log_success "All dependencies satisfied"
}

# Generate subdomain from website name
generate_subdomain() {
    local name="$1"
    # Convert to lowercase, replace spaces with dashes, remove special chars
    echo "$name" | tr '[:upper:]' '[:lower:]' | tr ' ' '-' | tr -cd 'a-z0-9-' | head -c 30
}

# Create static website files
create_website_files() {
    local subdomain="$1"
    local website_dir="$2"
    local html_content="$3"
    
    log_info "Creating website files for: $subdomain"
    
    # Create directory
    mkdir -p "$website_dir/$subdomain"
    
    # Write HTML content
    cat > "$website_dir/$subdomain/index.html" << 'EOF'
<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Website Generated by SiteSpark</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { 
            font-family: 'Plus Jakarta Sans', -apple-system, BlinkMacSystemFont, sans-serif;
            line-height: 1.6;
            color: #1e293b;
        }
        .container { max-width: 1200px; margin: 0 auto; padding: 0 20px; }
        header { 
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 4rem 0;
            text-align: center;
        }
        .badge { 
            display: inline-block;
            background: rgba(255,255,255,0.2);
            padding: 0.5rem 1rem;
            border-radius: 9999px;
            font-size: 0.875rem;
            margin-bottom: 1rem;
        }
        h1 { font-size: 3rem; margin-bottom: 1rem; font-weight: 700; }
        .subtitle { font-size: 1.25rem; opacity: 0.9; }
        main { padding: 4rem 0; }
        .features { 
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
            gap: 2rem;
            margin-top: 3rem;
        }
        .feature {
            padding: 2rem;
            background: #f8fafc;
            border-radius: 1rem;
            text-align: center;
        }
        .feature-icon {
            width: 64px;
            height: 64px;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            border-radius: 1rem;
            margin: 0 auto 1rem;
            display: flex;
            align-items: center;
            justify-content: center;
            color: white;
            font-size: 2rem;
        }
        footer {
            background: #1e293b;
            color: white;
            padding: 2rem 0;
            text-align: center;
            margin-top: 4rem;
        }
        .cta-button {
            display: inline-block;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 1rem 2rem;
            border-radius: 9999px;
            text-decoration: none;
            font-weight: 600;
            margin-top: 2rem;
            transition: transform 0.2s;
        }
        .cta-button:hover { transform: translateY(-2px); }
    </style>
    <link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;700&display=swap" rel="stylesheet">
</head>
<body>
    <header>
        <div class="container">
            <span class="badge">✨ AI Generated</span>
            <h1>Your Website is Live!</h1>
            <p class="subtitle">Created with SiteSpark AI in 1 minute</p>
            <a href="#" class="cta-button">Get Started</a>
        </div>
    </header>
    
    <main>
        <div class="container">
            <h2 style="text-align: center; font-size: 2rem; margin-bottom: 1rem;">Features</h2>
            <p style="text-align: center; color: #64748b; max-width: 600px; margin: 0 auto;">
                This website was automatically generated by AI. Customize it further with our dashboard.
            </p>
            
            <div class="features">
                <div class="feature">
                    <div class="feature-icon">⚡</div>
                    <h3>Lightning Fast</h3>
                    <p>Generated in under 1 minute with AI technology</p>
                </div>
                <div class="feature">
                    <div class="feature-icon">🎨</div>
                    <h3>Beautiful Design</h3>
                    <p>Modern glassmorphism design out of the box</p>
                </div>
                <div class="feature">
                    <div class="feature-icon">📱</div>
                    <h3>Mobile Ready</h3>
                    <p>Fully responsive on all devices</p>
                </div>
            </div>
        </div>
    </main>
    
    <footer>
        <div class="container">
            <p>Made with ❤️ by SiteSpark</p>
            <p style="opacity: 0.7; margin-top: 0.5rem;">© 2024 All rights reserved</p>
        </div>
    </footer>
</body>
</html>
EOF
    
    log_success "Website files created: $website_dir/$subdomain/index.html"
}

# Deploy to Dokploy via API
deploy_to_dokploy() {
    local subdomain="$1"
    local website_dir="$2"
    
    log_info "Deploying $subdomain to Dokploy..."
    
    # Create nginx.conf for this website
    cat > "$website_dir/$subdomain/nginx.conf" << EOF
server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;
    
    location / {
        try_files \$uri \$uri/ /index.html;
    }
    
    error_page 404 /index.html;
}
EOF

    # Create Dockerfile
    cat > "$website_dir/$subdomain/Dockerfile" << 'EOF'
FROM nginx:alpine
COPY . /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
EOF

    # Build and push Docker image
    local image_name="sitespark-$subdomain"
    log_info "Building Docker image: $image_name"
    
    docker build -t "$image_name:latest" "$website_dir/$subdomain"
    
    # TODO: Push to registry if configured
    # docker push "$image_name:latest"
    
    log_success "Docker image built: $image_name"
    
    # Alternative: Deploy as static files
    # Upload to Dokploy static hosting
    
    log_info "Website $subdomain ready for deployment"
    log_info "URL will be: https://$subdomain.yourdomain.com"
}

# Main deployment function
deploy_website() {
    local website_name="$1"
    local subdomain
    
    # Generate subdomain
    subdomain=$(generate_subdomain "$website_name")
    
    log_info "Starting deployment for: $website_name"
    log_info "Subdomain: $subdomain"
    
    # Create website directory
    local website_dir="$WEBSITES_DIR/$subdomain"
    mkdir -p "$website_dir"
    
    # Create files
    create_website_files "$subdomain" "$WEBSITES_DIR" ""
    
    # Deploy
    deploy_to_dokploy "$subdomain" "$WEBSITES_DIR"
    
    log_success "✅ Website deployed successfully!"
    log_info "🌐 URL: https://$subdomain.yourdomain.com"
    log_info "📁 Files: $website_dir"
}

# List all deployed websites
list_websites() {
    log_info "Listing deployed websites..."
    
    if [ ! -d "$WEBSITES_DIR" ]; then
        log_warn "No websites directory found"
        return
    fi
    
    for dir in "$WEBSITES_DIR"/*/; do
        if [ -d "$dir" ]; then
            local subdomain
            subdomain=$(basename "$dir")
            echo -e "${GREEN}●${NC} $subdomain"
            echo "  URL: https://$subdomain.yourdomain.com"
            echo "  Path: $dir"
            echo ""
        fi
    done
}

# Delete website
delete_website() {
    local subdomain="$1"
    local website_dir="$WEBSITES_DIR/$subdomain"
    
    if [ ! -d "$website_dir" ]; then
        log_error "Website not found: $subdomain"
        exit 1
    fi
    
    log_warn "Deleting website: $subdomain"
    rm -rf "$website_dir"
    log_success "Website deleted: $subdomain"
}

# Show usage
usage() {
    cat << EOF
SiteSpark Dokploy Deployment Script

Usage:
    ./deploy.sh [command] [options]

Commands:
    deploy <website-name>     Deploy a new website
    list                      List all deployed websites
    delete <subdomain>        Delete a website
    help                      Show this help message

Examples:
    ./deploy.sh deploy "Toko Kue Ani"
    ./deploy.sh list
    ./deploy.sh delete toko-kue-ani

Environment Variables:
    DOKPLOY_HOST    Dokploy host (default: localhost)
    DOKPLOY_PORT    Dokploy port (default: 3000)
    WEBSITES_DIR    Directory for website files (default: ./websites)
    PROJECT_NAME    Project name in Dokploy (default: sitespark)

EOF
}

# Main
main() {
    local command="${1:-help}"
    
    case "$command" in
        deploy)
            if [ -z "$2" ]; then
                log_error "Website name required"
                usage
                exit 1
            fi
            check_dependencies
            deploy_website "$2"
            ;;
        list)
            list_websites
            ;;
        delete)
            if [ -z "$2" ]; then
                log_error "Subdomain required"
                usage
                exit 1
            fi
            delete_website "$2"
            ;;
        help|--help|-h)
            usage
            ;;
        *)
            log_error "Unknown command: $command"
            usage
            exit 1
            ;;
    esac
}

main "$@"
